Features/popular person
waltad/movies-browser-panama pull request #25
Opened 2023-09-17 18:16 UTC by RobFyd

PersonalDeatailTile styled and responsiveness added. Please check and comment.

2023-09-17 21:51 UTC, P-Michalski requested changes
I think for now, there is so little to be merged yet. Also, on mobile display, the tile should in my opinion be stretched on entire width.

2023-09-22 22:49 UTC, RobFyd commented
The tile extends across the entire mobile view. Additionally, I added links from the API. I think the work done is ready to be added. Have fun with merging ;)

2023-09-23 06:20 UTC, waltad commented on src/common/PersonDetailTile/index.js
> +            <Label>Date of birth:</Label>
In the mobile version it should only be visible "Brith:"

2023-09-23 06:20 UTC, waltad commented on src/common/PersonDetailTile/index.js
> +            <Info>{birthplace}</Info>
In the mobile version description ("Place of birth:") should be under brithplace.

2023-09-23 06:20 UTC, waltad commented on src/common/PersonDetailTile/index.js
> +            <Info>{birthday}</Info>
the date format needs to be changed: DD.MM.RRRR

2023-09-23 06:20 UTC, waltad commented on src/apiURL.js
Good job. Apart from some minor styling tweaks, everything works fine.

2023-09-23 20:07 UTC, P-Michalski approved these changes

2023-09-23 20:07 UTC, P-Michalski commented
Cool, now we can merge 😄

2023-09-23 20:07 UTC, merged